### ISSUE TITLE
Request: realtime monitor of transport

### ISSUE THREAD

**Issue by fredamn76** [TekniskSupport/home-assistant-resrobot#20]
Is it possible to get realtime data from buss gps?

**Comment by TekniskSupport** [comment]
Well, Kind of if you are lucky enough to be living in a area where the real time data is available from the API the departure time is actually calculated from the "rTime" attribute instead of the "time" attribute, however if you need prescision you may want to up the update frequency of the integration (defaults to 10 minutes) as well as the sensors (every minute). Note that there are limits to how many requests you can do in a time interval (they will temporarily block your API key if you ask too often)

![image](https://user-images.githubusercontent.com/13868526/154340129-71e881cb-15f4-4b81-bc50-c2f0366bd4db.png)

**Comment by johanb2b** [comment]
Great work! It works good but i do not get the "rtTime" am i missing something in the configuration?

_"...{740067302@","stopExtId":"740067302","prognosisType":"PROGNOSED","time":"17:33:00","date":"2023-01-01","**rtTime":"17:36:00**","rtDate":"2023-01-01","reachable":true,"direction"..."_

**Comment by johanb2b** [comment]
> Great work! It works good but i do not get the "rtTime" am i missing something in the configuration?
> 
> _"...{740067302@","stopExtId":"740067302","prognosisType":"PROGNOSED","time":"17:33:00","date":"2023-01-01","**rtTime":"17:36:00**","rtDate":"2023-01-01","reachable":true,"direction"..."_

Ok. i changed two lines in my copy of sensor.py with an extra t and now it gives me the real time for my sensors.

From:
                   if "rTime" in data:
                        date_time = data["date"] +" "+ data["rTime"]
 To:
                   if "rtTime" in data:
                        date_time = data["date"] +" "+ data["rtTime"]

**Comment by TekniskSupport** [comment]
Oh, thanks! great work!
I've added your changes
