### ISSUE TITLE
Error on device update

### ISSUE THREAD

**Issue by fredamn76** [TekniskSupport/home-assistant-resrobot#6]
```
Logger: homeassistant.components.sensor
Source: custom_components/resrobot/sensor.py:163
Integration: Sensor (documentation, issues)
First occurred: 10:20:36 (6 occurrences)
Last logged: 10:20:37

resrobot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/resrobot/sensor.py", line 163, in async_update
    trips = self.filterResults(self._result['Departure'])
KeyError: 'Departure'
```
Jag har inte gjort några förändringar av integrationen men den uppdaterar inte sensorn längre.

**Comment by TekniskSupport** [comment]
I belive that this issue is from polling too much, and being restricted from getting any new departures
I have re-written the code quite a bit, i belive that the issue should be resolved with the new changes.

I added a helper sensor that takes the rest-result into an attribute and the other sensors use that helper to update their state, this way i don't have to poll new data as often

**Comment by TekniskSupport** [comment]
Please make the request manually and provide the result, the request command would look something like this:

`curl -s 'https://api.resrobot.se/v2/departureBoard?key=API-KEY&id=STOP-ID&maxJourneys=5&format=json'|jq .`

**Comment by fredamn76** [comment]
The latest update seems to have fixed this issue.
